/* Story Mode cheats. Button sequences are PlayStation input (Xbox is converted in app.js).
   Copied from the GTABase cheat list on 2026-10-05. Phone numbers match the keypad spelling of
   the PC code word except CATCHME and LIQUOR, which the game defines slightly differently. */
const CHEATS = [
  { name: "Max Health & Armor", ps: "Circle, L1, Triangle, R2, X, Square, Circle, Right, Square, L1, L1, L1", pc: "TURTLE", phone: "1-999-887-853", group: "player" },
  { name: "Invincibility (5 min)", ps: "Right, X, Right, Left, Right, R1, Right, Left, X, Triangle", pc: "PAINKILLER", phone: "1-999-724-654-5537", group: "player" },
  { name: "Raise Wanted Level", ps: "R1, R1, Circle, R2, Left, Right, Left, Right, Left, Right", pc: "FUGITIVE", phone: "1-999-3844-8483", group: "player" },
  { name: "Lower Wanted Level", ps: "R1, R1, Circle, R2, Right, Left, Right, Left, Right, Left", pc: "LAWYERUP", phone: "1-999-5299-3787", group: "player" },
  { name: "Recharge Special Ability", ps: "X, X, Square, R1, L1, X, Right, Left, X", pc: "POWERUP", phone: "1-999-769-3787", group: "player" },
  { name: "Fast Run", ps: "Triangle, Left, Right, Right, L2, L1, Square", pc: "CATCHME", phone: "1-999-2288-463", group: "player" },
  { name: "Fast Swim", ps: "Left, Left, L1, Right, Right, R2, Left, L2, Right", pc: "GOTGILLS", phone: "1-999-4684-4557", group: "player" },
  { name: "Give Parachute", ps: "Left, Right, L1, L2, R1, R2, R2, Left, Left, Right, L1", pc: "SKYDIVE", phone: "1-999-759-3483", group: "player" },
  { name: "Super Jump", ps: "Left, Left, Triangle, Triangle, Right, Right, Left, Right, Square, R1, R2", pc: "HOPTOIT", phone: "1-999-467-8648", group: "player" },
  { name: "Give Weapons & Ammo", ps: "Triangle, R2, Left, L1, X, Right, Triangle, Down, Square, L1, L1, L1", pc: "TOOLUP", phone: "1-999-866-587", group: "combat" },
  { name: "Slow-Mo Aim", ps: "Square, L2, R1, Triangle, Left, Square, L2, Right, X", pc: "DEADEYE", phone: "1-999-3323-393", group: "combat" },
  { name: "Explosive Melee", ps: "Right, Left, X, Triangle, R1, Circle, Circle, Circle, L2", pc: "HOTHANDS", phone: "1-999-4684-2637", group: "combat" },
  { name: "Explosive Ammo", ps: "Right, Square, X, Left, R1, R2, Left, Right, Right, L1, L1, L1", pc: "HIGHEX", phone: "1-999-444-439", group: "combat" },
  { name: "Flaming Ammo", ps: "L1, R1, Square, R1, Left, R2, R1, Left, Square, Right, L1, L1", pc: "INCENDIARY", phone: "1-999-462-363-4279", group: "combat" },
  { name: "Slow Motion", ps: "Triangle, Left, Right, Right, Square, R2, R1", pc: "SLOWMO", phone: "1-999-756-966", group: "world" },
  { name: "Drunk Mode", ps: "Triangle, Right, Right, Left, Right, Square, Circle, Left", pc: "LIQUOR", phone: "1-999-547-861", group: "world" },
  { name: "Moon Gravity", ps: "Left, Left, L1, R1, L1, Right, Left, L1, Left", pc: "FLOATER", phone: "1-999-356-2837", group: "world" },
  { name: "Skyfall", ps: "L1, L2, R1, R2, Left, Right, Left, Right, L1, L2, R1, R2, Left, Right, Left, Right", pc: "SKYFALL", phone: "1-999-759-3255", group: "world" },
  { name: "Slidey Cars", ps: "Triangle, R1, R1, Left, R1, L1, R2, L1", pc: "SNOWDAY", phone: "1-999-7669-329", group: "world" },
  { name: "Change Weather", ps: "R2, X, L1, L1, L2, L2, L2, Square", pc: "MAKEITRAIN", phone: "1-999-625-348-7246", group: "world" },
  { name: "Spawn BMX", ps: "Left, Left, Right, Right, Left, Right, Square, Circle, Triangle, R1, R2", pc: "BANDIT", phone: "1-999-226-348", group: "vehicle" },
  { name: "Spawn Buzzard", ps: "Circle, Circle, L1, Circle, Circle, Circle, L1, L2, R1, Triangle, Circle, Triangle", pc: "BUZZOFF", phone: "1-999-2899-633", group: "vehicle" },
  { name: "Spawn Caddy", ps: "Circle, L1, Left, R1, L2, X, R1, L1, Circle, X", pc: "HOLEIN1", phone: "1-999-4653-461", group: "vehicle" },
  { name: "Spawn Comet", ps: "R1, Circle, R2, Right, L1, L2, X, X, Square, R1", pc: "COMET", phone: "1-999-266-38", group: "vehicle" },
  { name: "Spawn Duster", ps: "Right, Left, R1, R1, R1, Left, Triangle, Triangle, X, Circle, L1, L1", pc: "FLYSPRAY", phone: "1-999-3597-7729", group: "vehicle" },
  { name: "Spawn Mallard Stunt Plane", ps: "Circle, Right, L1, L2, Left, R1, L1, L1, Left, Left, X, Triangle", pc: "BARNSTORM", phone: "1-999-227-678-676", group: "vehicle" },
  { name: "Spawn PCJ 600", ps: "R1, Right, Left, Right, R2, Left, Right, Square, Right, L2, L1, L1", pc: "ROCKET", phone: "1-999-762-538", group: "vehicle" },
  { name: "Spawn Rapid GT", ps: "R2, R2, L1, Circle, Right, L1, R1, Right, Left, Circle, R2", pc: "RAPIDGT", phone: "1-999-727-4348", group: "vehicle" },
  { name: "Spawn Sanchez", ps: "Circle, X, L1, Circle, Circle, L1, Circle, R1, R2, L2, L1, L1", pc: "OFFROAD", phone: "1-999-633-7623", group: "vehicle" },
  { name: "Spawn Stretch Limo", ps: "R2, Right, L2, Left, Left, R1, L1, Circle, Right", pc: "VINEWOOD", phone: "1-999-8463-9663", group: "vehicle" },
  { name: "Spawn Trashmaster", ps: "Circle, R1, Circle, R1, Left, Left, R1, L1, Circle, Right", pc: "TRASHED", phone: "1-999-8727-433", group: "vehicle" },
];
